In [3]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_validate
import numpy as np

def cross_validation_c(model,X,Y):

  cv = ShuffleSplit(n_splits=5, test_size=0.3, random_state=1)
  scores = cross_validate(model, X, Y, cv=cv , scoring=['f1_macro','f1_weighted','accuracy'])


  cv_f1=scores['test_f1_macro']
  cv_acc=scores['test_accuracy']
  cv_f1_wg=scores['test_f1_weighted']

  print("accuracy: %0.2f%% with a standard deviation of %0.2f" % (abs(cv_acc.mean()*100), cv_acc.std()))
  print("f1_macro score: %0.2f%% with a standard deviation of %0.2f" % (abs(cv_f1.mean()*100), cv_f1.std()))
  print("f1_weighted score: %0.2f%%  with a standard deviation of %0.2f" % (abs(cv_f1_wg.mean()*100), cv_f1_wg.std()))
  
def cross_validation_r(model,X,Y):

  cv = ShuffleSplit(n_splits=5, test_size=0.3, random_state=1)
  
  scores = cross_validate(model, X, Y, cv=cv , scoring=['neg_mean_squared_error','neg_mean_absolute_percentage_error','neg_mean_absolute_error'])


  cv_mape=scores['test_neg_mean_absolute_percentage_error']
  cv_mse=scores['test_neg_mean_squared_error']
  cv_mae=scores['test_neg_mean_absolute_error']
  
  print("MAPEs: ",cv_mape)
  print("MSEs: ",cv_mse)
  print("MAEs: ",cv_mae)

  print("MAPE: %0.2f%% with a standard deviation of %0.2f" % (abs(cv_mape.mean()*100), cv_mape.std()))
  print("MSE: %0.2f  with a standard deviation of %0.2f" % (abs(cv_mse.mean()), cv_mse.std()))
  print("MAE: %0.2f  with a standard deviation of %0.2f" % (abs(cv_mae.mean()), cv_mae.std()))
  

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
def print_classification_report(y_test,predictions):
  
  cf=confusion_matrix(y_test, predictions)
  print(cf)
  cr=classification_report(y_test, predictions,labels=[0,1,2,3,4],zero_division=False)
  print(cr)

In [4]:
from numpy import loadtxt
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.metrics import mean_absolute_percentage_error
from sklearn.metrics import mean_squared_error

# load data
dataset = loadtxt('g_dataset_class_2.csv', delimiter=",")
# split data into X and y
X = dataset[:,0:6]
Y = dataset[:,6]
# split data into train and test sets
seed = 6
test_size = 0.3

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)
# fit model no training data
model = XGBRegressor()

model.fit(X_train, y_train)
# make predictions for test data
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]

# evaluate predictions


# Cross validation
print("# cross validated evaluations")
print(cross_validation_r(model,X,Y))

# cross validated evaluations
MAPEs:  [-0.07797594 -0.07149602 -0.10173089 -0.05988536 -0.11160545]
MSEs:  [-1.72180348 -1.72707183 -2.03474367 -1.60556757 -2.07800019]
MAEs:  [-0.96647956 -0.91709182 -1.03720678 -0.81627081 -1.03377533]
MAPE: 8.45% with a standard deviation of 0.02
MSE: 1.83  with a standard deviation of 0.19
MAE: 0.95  with a standard deviation of 0.08
None


In [5]:
t = np.array([X[1],X[8],X[22],X[46]])
print(t)
y_pred = model.predict(t)
print(y_pred)

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0.]
 [1. 0. 2. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0.]]
[ 7.008057  13.994322  14.005598   5.1780515]


In [6]:
from sklearn import tree

from numpy import loadtxt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.metrics import mean_absolute_percentage_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate


# load data
dataset = loadtxt('g_dataset_class_2.csv', delimiter=",")
# split data into X and y
X = dataset[:,0:6]
Y = dataset[:,6]

# split data into train and test sets
seed = 6
test_size = 0.3

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)


# fit model no training data
model = tree.DecisionTreeRegressor()

model.fit(X_train, y_train)


# make predictions for test data
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]


#cross validation
print("# cross validated evaluations")
cross_validation_r(model,X,Y)

# cross validated evaluations
MAPEs:  [-0.07101795 -0.06696429 -0.11893939 -0.06712662 -0.0799513 ]
MSEs:  [-1.81818182 -2.13636364 -2.81818182 -1.95454545 -1.81818182]
MAEs:  [-0.81818182 -0.86363636 -1.09090909 -0.86363636 -0.81818182]
MAPE: 8.08% with a standard deviation of 0.02
MSE: 2.11  with a standard deviation of 0.37
MAE: 0.89  with a standard deviation of 0.10


In [42]:
t = np.array([X[1],X[8],X[22],X[46]])
print(t)
y_pred = model.predict(t)
print(y_pred)

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0.]
 [1. 0. 2. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0.]]
[ 7. 14. 14.  5.]


In [7]:
from sklearn import ensemble

from numpy import loadtxt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

from sklearn.metrics import mean_absolute_percentage_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate


# load data
dataset = loadtxt('g_dataset_class_2.csv', delimiter=",")
# split data into X and y
X = dataset[:,0:6]
Y = dataset[:,6]

# split data into train and test sets
seed = 6
test_size = 0.3

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)


# fit model no training data
model = ensemble.RandomForestRegressor()

model.fit(X_train, y_train)


# make predictions for test data
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]

# evaluate predictions

accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))


mape=mean_absolute_percentage_error(y_test, predictions)
mse=mean_squared_error(y_test, predictions)
mae= mean_absolute_error(y_test, predictions)


print("MAE: %.2f" % mae)
print("MAPE: %.2f%%" % (mape * 100.0))
print("MSE: %.2f" % mse)


#cross validation
print("# cross validated evaluations")
cross_validation_r(model,X,Y)

Accuracy: 40.91%
MAE: 0.82
MAPE: 8.99%
MSE: 1.45
# cross validated evaluations
MAPEs:  [-0.07817037 -0.06497971 -0.10115395 -0.05006953 -0.09467803]
MSEs:  [-1.38836364 -1.15536818 -1.57728636 -0.96571364 -1.37273182]
MAEs:  [-0.93727273 -0.83954545 -0.93681818 -0.69409091 -0.94318182]
MAPE: 7.78% with a standard deviation of 0.02
MSE: 1.29  with a standard deviation of 0.21
MAE: 0.87  with a standard deviation of 0.10


In [44]:
t = np.array([X[1],X[8],X[22],X[46]])
print(t)
y_pred = model.predict(t)
print(y_pred)

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0.]
 [1. 0. 2. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0.]]
[ 7.15 14.08 14.26  5.65]


In [8]:
from sklearn import svm

from numpy import loadtxt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

from sklearn.metrics import mean_absolute_percentage_error

# load data
dataset = loadtxt('g_dataset_class_2.csv', delimiter=",")
# split data into X and y
X = dataset[:,0:6]
Y = dataset[:,6]
# split data into train and test sets
seed = 6
test_size = 0.3

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)
# fit model no training data
model = svm.SVR()

model.fit(X_train, y_train)
# make predictions for test data
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]

# evaluate predictions


print("# cross validated evaluations")
cross_validation_r(model,X,Y)

# cross validated evaluations
MAPEs:  [-0.33764974 -0.16850919 -0.32441382 -0.25271444 -0.47578039]
MSEs:  [-11.55139364  -5.66306863 -11.93452823  -7.49456191 -16.85528009]
MAEs:  [-2.58581311 -1.78700679 -3.00866345 -1.97247099 -2.87743986]
MAPE: 31.18% with a standard deviation of 0.10
MSE: 10.70  with a standard deviation of 3.89
MAE: 2.45  with a standard deviation of 0.49


In [46]:
t = np.array([X[1],X[8],X[22],X[46]])
print(t)
y_pred = model.predict(t)
print(y_pred)

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0.]
 [1. 0. 2. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0.]]
[11.49235418 14.09981268 14.38413356 11.21728727]
